---
- name: Install Jenkins package
  ansible.builtin.dnf:
    name:
      - jenkins
    state: present

- name: Disable firewalld
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: jenkins
