OS:
  Debian:
    sudo_group: sudo
  Fedora:
    sudo_group: wheel

typical_packages:
  - jq
  - htop
  - tmux
  - screen
  - mc
  - net-tools
  - python3-libselinux

# Набор типовых настроек шабона sshd_config.j2 для всех хостов
# В последствии доп опции можно подбрасывать в файлы /etc/ssh/sshd_config.d/*.conf (опция Include /etc/ssh/sshd_config.d/*.conf)
sshd:
  PasswordAuthentication: "yes"
  PermitRootLogin: "prohibit-password"

